CRUDMedicamentos/Models/ViewModels/MedicamentoViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace MedicamentosCRUD.Models.ViewModels
{
    public class MedicamentoViewModel
    {
        //IIDMEDICAMENTO|NOMBRE|CONCENTRACION|IIDFORMAFARMACEUTICA|PRECIO|STOCK|PRESENTACION|BHABILITADO
        public string Iidmedicamento { get; set; }
        public string Nombre { get; set; }
        public string Concentracion { get; set; }
        public string Iidformafarmaceutica { get; set; }
        public string Precio { get; set; }
        public string Stock { get; set; }
        public string Presentacion { get; set; }
        public string Bhabilitado { get; set; }
    }
}

CRUDMedicamentos/Controllers/MedicamentoController.cs
using MedicamentosCRUD.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CRUDMedicamentos.Controllers
{
    public class MedicamentoController : Controller
    {

        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(string usuario, string contraseña)
        {
            string fileName = @"C:\dotNET\Proyectos\CRUDMedicamentos\CRUDMedicamentos\Models\BD\Usuarios.txt";
            List<string> lineas = new List<string>();

            using (StreamReader reader = new StreamReader(fileName))
            {
                string line;

                line = reader.ReadLine();
                while ((line = reader.ReadLine()) != null)
                {
                    lineas.Add(line);
                }
                foreach(var l in lineas)
                {
                    var user = l.Split('|');
                    if (user[3] == usuario && user[4] == contraseña)
                    {
                        return Redirect("~/Medicamento/");

                    }
                    else
                    {
                    }
                }
            }

            return View();
        }
        // GET: Medicamento
        public ActionResult Index()
        {
            List<ListMedicamentoViewModel> lista = new List<ListMedicamentoViewModel>();
            string fileName = @"C:\dotNET\Proyectos\CRUDMedicamentos\CRUDMedicamentos\Models\BD\Medicamentos.txt";

            using (StreamReader reader = new StreamReader(fileName))
            {
                string line;
                line = reader.ReadLine();
                while ((line = reader.ReadLine()) != null)
                {
                    //IIDMEDICAMENTO|NOMBRE|CONCENTRACION|IIDFORMAFARMACEUTICA|PRECIO|STOCK|PRESENTACION|BHABILITADO

                    var linea = line.Split('|');
                    if(linea.Count() > 1)
                    {
                        ListMedicamentoViewModel medicamento = new ListMedicamentoViewModel();
                        medicamento.Iidmedicamento = linea[0];
                        medicamento.Nombre = linea[1];
                        medicamento.Concentracion = linea[2];
                        medicamento.Iidformafarmaceutica = linea[3];
                        medicamento.Precio = linea[4];
                        medicamento.Stock = linea[5];
                        medicamento.Presentacion = linea[6];
                        medicamento.Bhabilitado = linea[7];
                        lista.Add(medicamento);
                    }

                }
            }

            return View(lista);
        }

        public ActionResult Agregar()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Agregar(MedicamentoViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    string fileName = @"C:\dotNET\Proyectos\CRUDMedicamentos\CRUDMedicamentos\Models\BD\Medicamentos.txt";
                    using (StreamWriter sw = new StreamWriter(fileName, true))
                    {
                        string medicamento = model.Iidmedicamento + "|" + model.Nombre + "|" + model.Concentracion + "|" + model.Iidformafarmaceutica + "|" + model.Precio + "|" + model.Stock + "|" + model.Presentacion + "|" + model.Bhabilitado;
                        sw.Write(medicamento);
                    }
                    return Redirect("~/Medicamento/");
                }
                return View(model);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        public ActionResult Editar(int id)
        {
            MedicamentoViewModel model = new MedicamentoViewModel();
            string fileName = @"C:\dotNET\Proyectos\CRUDMedicamentos\CRUDMedicamentos\Models\BD\Medicamentos.txt";
            string[] linea ;
            using (var sr = new StreamReader(fileName))
            {
                for (int i = 1; i <= id; i++)
                    sr.ReadLine();
                linea = sr.ReadLine().Split('|');
            }
            model.Iidmedicamento = linea[0];
            model.Nombre = linea[1];
            model.Concentracion = linea[2];
            model.Iidformafarmaceutica = linea[3];
            model.Precio = linea[4];
            model.Stock = linea[5];
            model.Presentacion = linea[6];
            model.Bhabilitado = linea[7];

            return View(model);
        }
        [HttpPost]
        public ActionResult Editar(MedicamentoViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    string fileName = @"C:\dotNET\Proyectos\CRUDMedicamentos\CRUDMedicamentos\Models\BD\Medicamentos.txt";
                    List<string> lineas = new List<string>();

                    using (StreamReader reader = new StreamReader(fileName))
                    {
                        string line;
                       
                        line = reader.ReadLine();
                        while ((line = reader. ReadLine()) != null)
                        {
                            lineas.Add(line);
                        }
                    }
                    using (StreamWriter sw = new StreamWriter(fileName, false))
                    {
                        string medicamento = model.Iidmedicamento + "|" + model.Nombre + "|" + model.Concentracion + "|" + model.Iidformafarmaceutica + "|" + model.Precio + "|" + model.Stock + "|" + model.Presentacion + "|" + model.Bhabilitado;

                        lineas[Convert.ToInt32(model.Iidmedicamento) - 1] = medicamento;
                        string contenido = "IIDMEDICAMENTO|NOMBRE|CONCENTRACION|IIDFORMAFARMACEUTICA|PRECIO|STOCK|PRESENTACION|BHABILITADO\n";
                        foreach(var l in lineas)
                        {
                            contenido += l.Trim() + "\n";
                        }
                        sw.Write(contenido);
                    }
                    return Redirect("~/Medicamento/");
                }
                return View(model);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        [HttpGet]
        public ActionResult Eliminar(int id)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    string fileName = @"C:\dotNET\Proyectos\CRUDMedicamentos\CRUDMedicamentos\Models\BD\Medicamentos.txt";
                    List<string> lineas = new List<string>();

                    using (StreamReader reader = new StreamReader(fileName))
                    {
                        string line;

                        line = reader.ReadLine();
                        while ((line = reader.ReadLine()) != null)
                        {
                            lineas.Add(line);
                        }
                    }
                    using (StreamWriter sw = new StreamWriter(fileName, false))
                    {

                        lineas[Convert.ToInt32(id) - 1] = "";
                        string contenido = "IIDMEDICAMENTO|NOMBRE|CONCENTRACION|IIDFORMAFARMACEUTICA|PRECIO|STOCK|PRESENTACION|BHABILITADO\n";
                        foreach (var l in lineas)
                        {
                            contenido += l.Trim() + "\n";
                        }
                        sw.Write(contenido);
                    }
                }
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }

            return Redirect("~/Medicamento/");
        }

    }
}

CRUDMedicamentos/Views/Medicamento/Agregar.cshtml
@model MedicamentosCRUD.Models.ViewModels.MedicamentoViewModel

@{
    ViewBag.Title = "Agregar medicamento";
}
@{ 
    string fileName = @"C:\dotNET\Proyectos\CRUDMedicamentos\CRUDMedicamentos\Models\BD\FormaFarmaceutica.txt";
    List<string> lineas = new List<string>();
    var listado = new List<SelectListItem>();

    using (StreamReader reader = new StreamReader(fileName))
    {
        string line;

        line = reader.ReadLine();
        while ((line = reader.ReadLine()) != null)
        {
            lineas.Add(line);
        }
        foreach (var l in lineas)
        {
            var select = l.Split('|');
            if (select[2] == "1") //si esta habilitado
            {
                listado.Add(new SelectListItem()
                {
                    Text = select[1],
                    Value=select[0]
                }) ;
            }
        }
    }

}
<h2>Agregar</h2>

@using (Html.BeginForm("Agregar", "Medicamento", FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Iidmedicamento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Iidmedicamento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Iidmedicamento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Concentracion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Concentracion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Concentracion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Iidformafarmaceutica, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("dropdownlist", listado, htmlAttributes: new {@class="form-control col-md-2"})
                @Html.ValidationMessageFor(model => model.Iidformafarmaceutica, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Precio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Precio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Precio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Stock, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Stock, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Stock, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Presentacion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Presentacion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Presentacion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Bhabilitado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Bhabilitado, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Bhabilitado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Agregar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar al listado", "Index")
</div>

CRUDMedicamentos/Views/Medicamento/Editar.cshtml
@model MedicamentosCRUD.Models.ViewModels.MedicamentoViewModel

@{
    ViewBag.Title = "Editar medicamento";
}
@{
    string fileName = @"C:\dotNET\Proyectos\CRUDMedicamentos\CRUDMedicamentos\Models\BD\FormaFarmaceutica.txt";
    List<string> lineas = new List<string>();
    var listado = new List<SelectListItem>();

    using (StreamReader reader = new StreamReader(fileName))
    {
        string line;

        line = reader.ReadLine();
        while ((line = reader.ReadLine()) != null)
        {
            lineas.Add(line);
        }
        foreach (var l in lineas)
        {
            var select = l.Split('|');
            if (select[2] == "1") //si esta habilitado
            {
                listado.Add(new SelectListItem()
                {
                    Text = select[1],
                    Value = select[0]
                });
            }
        }
    }

}
<h2>Editar</h2>

@using (Html.BeginForm("Editar", "Medicamento", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.HiddenFor(e => e.Iidmedicamento)
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Iidmedicamento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Iidmedicamento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Iidmedicamento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Concentracion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Concentracion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Concentracion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Iidformafarmaceutica, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model=>model.Iidformafarmaceutica,listado, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Iidformafarmaceutica, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Precio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Precio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Precio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Stock, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Stock, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Stock, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Presentacion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Presentacion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Presentacion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Bhabilitado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Bhabilitado, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Bhabilitado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Agregar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar al listado", "Index")
</div>

CRUDMedicamentos/Views/Medicamento/Index.cshtml
@model List<MedicamentosCRUD.Models.ViewModels.ListMedicamentoViewModel>
@{
    ViewBag.Title = "Listado de medicamentos";
    //IIDMEDICAMENTO|NOMBRE|CONCENTRACION|IIDFORMAFARMACEUTICA|PRECIO|STOCK|PRESENTACION|BHABILITADO
}

<h2>Listado de medicamentos</h2>

<div class="row" style="text-align:right">
    <a href="~/Medicamento/Agregar" class="btn btn-primary">Agregar</a>
</div>
<br />
<div class="row">
    <div class="col-md-12">
        <div class="container">
            <div class="table-responsive">
                <div class="table-wrapper">
                    <table class="table table-striped table-hover table-bordered">
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th>Nombre</th>
                                <th>Concentración</th>
                                <th>Id Forma Farmaceutica</th>
                                <th>Precio</th>
                                <th>Stock</th>
                                <th>Presentación</th>
                                <th>Habilitado</th>
                                <th>Editar</th>
                                <th>Eliminar</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var medicamento in Model)
                            {
                                <tr>
                                    <td>@medicamento.Iidmedicamento</td>
                                    <td>@medicamento.Nombre</td>
                                    <td>@medicamento.Concentracion</td>
                                    <td>@medicamento.Iidformafarmaceutica</td>
                                    <td>@medicamento.Precio</td>
                                    <td>@medicamento.Stock</td>
                                    <td>@medicamento.Presentacion</td>
                                    <td>@medicamento.Bhabilitado</td>
                                    <td>
                                        <a href="~/Medicamento/Editar/@medicamento.Iidmedicamento"><span class="glyphicon glyphicon-cog"></span></a>
                                    </td>
                                    <td>

                                        <a href="~/Medicamento/Eliminar/@medicamento.Iidmedicamento"><span class="glyphicon glyphicon-trash"></span> </a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

CRUDMedicamentos/Views/Medicamento/Login.cshtml
@model CRUDMedicamentos.Models.ViewModels.UsuarioViewModel

@{
    ViewBag.Title = "Login";
}

<h2>Login</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.usuario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.usuario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.usuario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.contraseña, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.contraseña, new { htmlAttributes = new { @class = "form-control", type="password" } })
                @Html.ValidationMessageFor(model => model.contraseña, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Iniciar sesión" class="btn btn-default" />
            </div>
        </div>
    </div>
}